# Generated by Django 3.2.5 on 2021-07-09 20:47

from django.db import migrations, models
import kafka_test.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.CharField(default=kafka_test.models.random_value, max_length=64)),
            ],
        ),
    ]
