# Generated by Django 3.2.5 on 2021-07-14 07:26

from django.db import migrations, models
import kafka_example.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.CharField(default=kafka_example.models.random_value, max_length=64)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
